### ISSUE TITLE
Filters like includeOnly not working in .looprc

### ISSUE THREAD

**Issue by exp0nge** [mateodelnorte/loop-things#11]
I have a filter like `includeOnly: ['blah/', 'foo']` but when I run `loop ..` it doesn't follow the rules.

**Comment by mateodelnorte** [comment]
If you're executing through code, be sure to provide a fully qualified path. You can do that via `[path.resolve('blah'), path.resolve('foo')]`. 

If you're using the command line, the syntax is loop --include-only blah, foo

**Comment by exp0nge** [comment]
Is it not possible to use the filters from the command line but that are specified in .looprc? 

For example: I'm working on a set of microservices, so I don't want to work across all repos yet, just a handful. I want to avoid having to type --include-only multiple times.

**Comment by mateodelnorte** [comment]
You just use a comma delimited list of directories after the option
declaration

**Comment by mateodelnorte** [comment]
loop pwd --include-only dir1, dir2 ...

**Comment by exp0nge** [comment]
Sorry, what I meant was I don't want to bother typing --include-only at all. I was hoping looprc would take care of that.

**Comment by mateodelnorte** [comment]
The ignore attribute in .looprc will ignore any directories you don't want
to run in. Is that what you want, or something different?

**Comment by exp0nge** [comment]
Okay, that should work. Thanks.

**Comment by exp0nge** [comment]
That would work as a workaround but really inconvenient when you have a lot of repos.
