### ISSUE TITLE
Trim whitespaces on directories list

### ISSUE THREAD

**Issue by lexod** [mateodelnorte/loop-things#9]
Currently if you put 
`loop "git status" --exclude dir1,dir2,dir3`
will do the trick, but if you will add whitespaces on the beginning or in the end of dir it will fail
`loop "git status" --exclude dir1 , dir2 , dir3`

**Comment by mateodelnorte** [comment]
fixed in 12916844be8887854f9d4d3e6105f7d545b61a25

published to @0.0.21
